const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const startScreen=document.querySelector('#start'),gameOverScreen=document.querySelector('#gameover');
const ui={meters:meters,clues:clues,score:score,heat:document.querySelector('#heat i'),message};
const hero=new Image(),attack=new Image(); hero.src='../game/hero.png'; attack.src='../comics/scenes/comic_trouble_baby_attack.png';
let W,H,DPR,run=false,last=0,touch=null,state;
const lanes=[-1,0,1], palettes={prison:{sky:'#161b22',far:'#303944',road:'#20252c',edge:'#79818c',accent:'#e6b94b'},city:{sky:'#79a9c3',far:'#d0b98f',road:'#45484c',edge:'#d4c6a8',accent:'#e35f4b'}};
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)} addEventListener('resize',resize);resize();
function reset(){state={lane:0,target:0,jump:0,jumpV:0,slide:0,speed:19,distance:0,score:0,clues:0,chase:22,streak:0,objects:[],spawn:0,section:'prison',flash:0,power:null,powerT:0};for(let z=35;z<155;z+=14)spawnRow(z);sync()}
function rand(a,b){return a+Math.random()*(b-a)}
function spawnRow(z=150){const difficulty=Math.min(1,state.distance/3500),available=[...lanes];let blocked=Math.random()<.7+(.2*difficulty)?Math.random()<.65?1:2:0;if(blocked===3)blocked=2;for(let i=0;i<blocked;i++){const lane=available.splice(Math.floor(Math.random()*available.length),1)[0];const r=Math.random();state.objects.push({lane,z,type:r<.44?'barrier':r<.72?'high':r<.9?'moving':'hole',phase:rand(0,6.28),hit:false})}const safe=available[Math.floor(Math.random()*available.length)];if(Math.random()<.82)state.objects.push({lane:safe,z:z+rand(2,5),type:Math.random()<.3?'clue':'coin',phase:0,hit:false});if(Math.random()<.07)state.objects.push({lane:safe,z:z+8,type:['shield','magnet','slow','jump'][Math.floor(Math.random()*4)],phase:0,hit:false})}
function project(lane,z,y=0){const horizon=H*.25,bottom=H*.91,t=Math.max(0,Math.min(1,1-z/165)),ease=t*t;return{x:W/2+lane*W*.235*ease,y:horizon+(bottom-horizon)*ease-y*ease,scale:.12+.9*ease}}
function input(k){if(!run)return;if(k==='left')state.target=Math.max(-1,state.target-1);if(k==='right')state.target=Math.min(1,state.target+1);if(k==='up'&&state.jump===0){state.jumpV=860;state.jump=.01}if(k==='down'&&state.jump<8)state.slide=.72}
addEventListener('keydown',e=>{const m={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',Space:'up',ArrowDown:'down',KeyS:'down'};if(m[e.code]){e.preventDefault();input(m[e.code])}});
canvas.addEventListener('pointerdown',e=>touch=[e.clientX,e.clientY]);canvas.addEventListener('pointerup',e=>{if(!touch)return;let dx=e.clientX-touch[0],dy=e.clientY-touch[1];Math.abs(dx)>Math.abs(dy)?input(dx>0?'right':'left'):input(dy>0?'down':'up');touch=null});
function messageText(t){ui.message.textContent=t;ui.message.style.opacity=1;clearTimeout(messageText.t);messageText.t=setTimeout(()=>ui.message.style.opacity=0,1200)}
function collide(o){if(o.hit||o.z>10||o.z<1||Math.abs(state.lane-o.lane)>.42)return;const airborne=state.jump>85,sliding=state.slide>0;if(o.type==='coin'||o.type==='clue'){o.hit=true;state[o.type==='clue'?'clues':'score']++;state.score+=o.type==='clue'?250:35;state.streak++;return}if(['shield','magnet','slow','jump'].includes(o.type)){o.hit=true;state.power=o.type;state.powerT=7;messageText({shield:'ЩИТ!',magnet:'МАГНИТ УЛИК!',slow:'ВРЕМЯ ЗАМЕДЛЕНО!',jump:'СУПЕРПРЫЖОК!'}[o.type]);return}let safe=o.type==='barrier'&&airborne||o.type==='hole'&&airborne||o.type==='high'&&sliding;if(!safe){o.hit=true;if(state.power==='shield'){state.power=null;state.powerT=0;messageText('Щит спас Асыла!')}else{state.chase=Math.min(100,state.chase+23);state.speed*=.73;state.streak=0;state.flash=.25;messageText('Карапуз ближе!')}}}
function update(dt){if(!run)return;state.distance+=state.speed*dt;state.speed=Math.min(43,state.speed+dt*.42);if(state.power==='slow')state.speed=Math.max(18,state.speed-dt*.2);state.chase=Math.max(8,state.chase-dt*(state.streak>6?2.2:.5));state.lane+=(state.target-state.lane)*Math.min(1,dt*12);if(state.jump>0){state.jump+=state.jumpV*dt;state.jumpV-=1900*dt;if(state.jump<=0){state.jump=0;state.jumpV=0}}state.slide=Math.max(0,state.slide-dt);state.powerT=Math.max(0,state.powerT-dt);if(!state.powerT)state.power=null;state.flash=Math.max(0,state.flash-dt);const scroll=state.speed*dt*1.75;state.objects.forEach(o=>{o.z-=scroll;if(o.type==='moving')o.lane=Math.max(-1,Math.min(1,o.lane+Math.sin(state.distance*.035+o.phase)*dt*.65));if(state.power==='magnet'&&(o.type==='coin'||o.type==='clue')&&o.z<34)o.lane+=(state.lane-o.lane)*dt*7;collide(o)});state.objects=state.objects.filter(o=>o.z>-8&&!o.hit);state.spawn-=scroll;while(state.spawn<0){spawnRow(150-state.spawn);state.spawn+=rand(11,16)-Math.min(4,state.distance/1400)}if(state.distance>1200&&state.section==='prison'){state.section='city';messageText('ПОБЕГ УДАЛСЯ — ГОРОД!')}state.score+=Math.floor(state.speed*dt*2);sync();if(state.chase>=100)end()}
function sync(){ui.meters.textContent=Math.floor(state.distance);ui.clues.textContent=state.clues;ui.score.textContent=state.score;ui.heat.style.width=state.chase+'%'}
function drawWorld(){const p=palettes[state.section],h=H*.25;ctx.fillStyle=p.sky;ctx.fillRect(0,0,W,H);ctx.fillStyle=p.far;ctx.fillRect(0,h*.35,W,h*.75);for(let i=0;i<12;i++){let x=(i*137-state.distance*3)%(W+180)-90,w=state.section==='prison'?90:rand(55,110),bh=state.section==='prison'?h*.52:h*(.25+(i%4)*.1);ctx.fillStyle=i%2?'#242c34':'#323b44';if(state.section==='city')ctx.fillStyle=i%2?'#d6b690':'#b97d69';ctx.fillRect(x,h-bh,w,bh);ctx.fillStyle=p.accent;for(let y=h-bh+15;y<h-12;y+=25)for(let wx=x+12;wx<x+w-8;wx+=24)ctx.fillRect(wx,y,8,8)}ctx.fillStyle=p.road;ctx.beginPath();ctx.moveTo(W*.43,h);ctx.lineTo(W*.04,H);ctx.lineTo(W*.96,H);ctx.lineTo(W*.57,h);ctx.fill();ctx.strokeStyle=p.edge;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(W*.43,h);ctx.lineTo(W*.04,H);ctx.moveTo(W*.57,h);ctx.lineTo(W*.96,H);ctx.stroke();ctx.strokeStyle='#e6d9b2aa';ctx.lineWidth=3;ctx.setLineDash([18,24]);for(const l of [-.5,.5]){ctx.beginPath();ctx.moveTo(W/2,h);ctx.lineTo(W/2+l*W*.47,H);ctx.stroke()}ctx.setLineDash([]);if(state.section==='prison'){ctx.strokeStyle='#59636e';ctx.lineWidth=8;for(let y=h+25;y<H;y+=90){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W*.22,y+20);ctx.stroke();ctx.beginPath();ctx.moveTo(W,y);ctx.lineTo(W*.78,y+20);ctx.stroke()}}}
function drawObject(o){let y=0;if(o.type==='coin'||o.type==='clue'||['shield','magnet','slow','jump'].includes(o.type))y=45+Math.sin(performance.now()/180+o.z)*8;const q=project(o.lane,o.z,y),s=q.scale;if(s<.13)return;ctx.save();ctx.translate(q.x,q.y);if(o.type==='barrier'||o.type==='moving'){ctx.fillStyle=state.section==='prison'?'#8f5e37':'#df6b48';ctx.fillRect(-45*s,-66*s,90*s,66*s);ctx.strokeStyle='#1b1512';ctx.lineWidth=4*s;ctx.strokeRect(-45*s,-66*s,90*s,66*s);ctx.fillStyle='#f6c453';ctx.fillRect(-40*s,-48*s,80*s,12*s)}else if(o.type==='high'){ctx.fillStyle='#6a737d';ctx.fillRect(-62*s,-120*s,124*s,25*s);ctx.fillRect(-62*s,-120*s,12*s,120*s);ctx.fillRect(50*s,-120*s,12*s,120*s)}else if(o.type==='hole'){ctx.fillStyle='#050506';ctx.beginPath();ctx.ellipse(0,-4*s,55*s,18*s,0,0,7);ctx.fill()}else{let icon={coin:'★',clue:'🔎',shield:'◆',magnet:'∩',slow:'◷',jump:'↑'}[o.type];ctx.font=`900 ${Math.max(12,48*s)}px system-ui`;ctx.textAlign='center';ctx.fillStyle=o.type==='clue'?'#72c3db':'#f6c453';ctx.strokeStyle='#171717';ctx.lineWidth=5*s;ctx.strokeText(icon,0,0);ctx.fillText(icon,0,0)}ctx.restore()}
function drawCharacters(){const q=project(state.lane,1,state.jump),slide=state.slide>0;ctx.save();ctx.translate(q.x,q.y);ctx.scale(slide?1.3:1,slide?.58:1);ctx.rotate((state.target-state.lane)*-.12);if(hero.complete)ctx.drawImage(hero,-72,-220,144,220);ctx.restore();const chaseY=H*(.98-state.chase*.0021),size=70+state.chase*.55;ctx.save();ctx.translate(W/2+Math.sin(performance.now()/100)*5,chaseY);ctx.rotate(Math.sin(performance.now()/85)*.05);if(attack.complete)ctx.drawImage(attack,760,120,420,390,-size/2,-size,size,size*.93);else{ctx.fillStyle='#171717';ctx.beginPath();ctx.arc(0,-size/2,size/2,0,7);ctx.fill()}ctx.restore()}
function draw(){drawWorld();state.objects.slice().sort((a,b)=>b.z-a.z).forEach(drawObject);drawCharacters();if(state.flash){ctx.fillStyle=`rgba(229,87,79,${state.flash})`;ctx.fillRect(0,0,W,H)}ctx.fillStyle='#fff';ctx.font='800 14px system-ui';ctx.fillText(state.section==='prison'?'ТЮРЬМА · ПОБЕГ':'ГОРОД · ПОГОНЯ',18,H-22);if(state.power){ctx.textAlign='right';ctx.fillStyle='#f6c453';ctx.font='900 18px system-ui';ctx.fillText(state.power.toUpperCase(),W-18,H-22);ctx.textAlign='left'}}
function frame(t){let dt=Math.min(.034,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function startRun(){reset();run=true;last=performance.now();startScreen.style.display='none';gameOverScreen.style.display='none';canvas.focus()}
function end(){run=false;finalTitle.textContent=state.distance>1200?'Почти скрылся в городе!':'Побег оборвался';finalStats.textContent=`Дистанция: ${Math.floor(state.distance)} м · Улики: ${state.clues} · Счёт: ${state.score}`;gameOverScreen.style.display='grid'}
play.onclick=startRun;again.onclick=startRun;reset();draw();
